### PR TITLE
feat: support custom SQL Admin API endpoint

### PR DESCRIPTION
**Pull request by edosrecki**
Allows library users to optionally pass custom
SQL Admin API endpoint in the Connector constructor.

Fixes: #64

### CODE REVIEW

**Comment by jackwotherspoon** [comment]
Thanks for this @edosrecki! You are absolutely on a roll, we appreciate it greatly! Will let @ruyadorno take a look at this

**Review by ruyadorno — CHANGES_REQUESTED** [review]

**Comment by edosrecki** [comment]
@ruyadorno, thank you for the review. I addressed your comments. Please take another look.

**Comment by ruyadorno** [comment]
thank you @edosrecki I'll take a look as soon as possible!

**Review by ruyadorno — COMMENTED** [review]
hi @edosrecki sorry about the delay! Can I ask you for one more change please, in order to align more with the different implementations (like https://github.com/GoogleCloudPlatform/cloud-sql-python-connector and https://github.com/GoogleCloudPlatform/cloud-sql-go-connector) the team has been trying more and more to stick with the same names whenever possible.

With that in mind I'd like to ask you to rename the `sqlAdminRootUrl` -> `sqladminApiEndpoint`.

That's the last blocking change here, otherwise the PR LGTM 👍

**Comment by edosrecki** [comment]
@ruyadorno no problem, done that!

**Review by ruyadorno — APPROVED** [review]
awesome! thanks @edosrecki! LGTM 👍

**Pull request merged**
