### PR TITLE
feat: Allow connector to accept loginAuth to pass it down to sqlAdminFetcher

### PR DESCRIPTION
**Pull request by Anoupz**
## Change Description

Allow connector to accept custom auth as arg to be able to pass it down to sqlAdminFetcher which can rely on custom auth or default auth if none is provided. 

## Relevant issues:

- Fixes https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/issues/200

### CODE REVIEW

**Comment by jackwotherspoon** [comment]
@Anoupz Thanks for the contribution! Would you mind maybe adding a quick test to https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/blob/main/test/connector.ts that covers passing in a credential?

**Comment by edosrecki** [comment]
@Anoupz , @jackwotherspoon 

What about the `auth` here: https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/blob/0d34e7bb2d5977a6b1ee50455d9682e1fd7f2aae/src/sqladmin-fetcher.ts#L76

**Comment by jackwotherspoon** [comment]
> What about the `auth` here:
> 
> https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/blob/0d34e7bb2d5977a6b1ee50455d9682e1fd7f2aae/src/sqladmin-fetcher.ts#L76

@Anoupz the way the Connector works is it has two credential Google Auth objects, each with different access scopes. The `loginAuth` is used for [logging in with automatic IAM database authentication](https://cloud.google.com/sql/docs/postgres/iam-logins#log-in-with-automatic) and has the `'https://www.googleapis.com/auth/sqlservice.login'` scopes required to purely login to a Cloud SQL database. The second Google Auth object that @edosrecki is pointing out is used for authorization and to authorize the client used to make Cloud SQL Admin API calls (aka does the person connecting have the proper permissions to connect to Cloud SQL) and requires the `'https://www.googleapis.com/auth/sqlservice.admin'`.

Both of these credentials must belong to the same IAM Principal in order to successfully connect with IAM database authentication. Thus, we need to support setting both of these to the custom credentials passed in. 

In Python we can pass in a single credentials object because the `google-auth` library allows [credentials to be re-scoped](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/blob/main/google/cloud/sql/connector/refresh_utils.py#L198) (hence we can pass in a single credentials object and scope it as required to satisfy both auth credentials). I wonder if something similar is possible for the node [`google-auth-library`](https://www.npmjs.com/package/google-auth-library)?

**Comment by Anoupz** [comment]
> > What about the `auth` here:
> > https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/blob/0d34e7bb2d5977a6b1ee50455d9682e1fd7f2aae/src/sqladmin-fetcher.ts#L76
> 
> @Anoupz the way the Connector works is it has two credential Google Auth objects, each with different access scopes. The `loginAuth` is used for [logging in with automatic IAM database authentication](https://cloud.google.com/sql/docs/postgres/iam-logins#log-in-with-automatic) and has the `'https://www.googleapis.com/auth/sqlservice.login'` scopes required to purely login to a Cloud SQL database. The second Google Auth object that @edosrecki is pointing out is used for authorization and to authorize the client used to make Cloud SQL Admin API calls (aka does the person connecting have the proper permissions to connect to Cloud SQL) and requires the `'https://www.googleapis.com/auth/sqlservice.admin'`.
> 
> Both of these credentials must belong to the same IAM Principal in order to successfully connect with IAM database authentication. Thus, we need to support setting both of these to the custom credentials passed in.
> 
> In Python we can pass in a single credentials object because the `google-auth` library allows [credentials to be re-scoped](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/blob/main/google/cloud/sql/connector/refresh_utils.py#L198) (hence we can pass in a single credentials object and scope it as required to satisfy both auth credentials). I wonder if something similar is possible for the node [`google-auth-library`](https://www.npmjs.com/package/google-auth-library)?

Humm, When I tested this I did not encounter any issue. Let me check again

**Comment by jackwotherspoon** [comment]
> Humm, When I tested this I did not encounter any issue. Let me check again

@Anoupz are you using IAM database authentication to login for your use-case or regular username/password database auth?

**Comment by Anoupz** [comment]
> > Humm, When I tested this I did not encounter any issue. Let me check again
> 
> @Anoupz are you using IAM database authentication to login for your use-case or regular username/password database auth?

I am using IAM database authentication.

**Comment by Anoupz** [comment]
> > > What about the `auth` here:
> > > https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/blob/0d34e7bb2d5977a6b1ee50455d9682e1fd7f2aae/src/sqladmin-fetcher.ts#L76
> > 
> > 
> > @Anoupz the way the Connector works is it has two credential Google Auth objects, each with different access scopes. The `loginAuth` is used for [logging in with automatic IAM database authentication](https://cloud.google.com/sql/docs/postgres/iam-logins#log-in-with-automatic) and has the `'https://www.googleapis.com/auth/sqlservice.login'` scopes required to purely login to a Cloud SQL database. The second Google Auth object that @edosrecki is pointing out is used for authorization and to authorize the client used to make Cloud SQL Admin API calls (aka does the person connecting have the proper permissions to connect to Cloud SQL) and requires the `'https://www.googleapis.com/auth/sqlservice.admin'`.
> > Both of these credentials must belong to the same IAM Principal in order to successfully connect with IAM database authentication. Thus, we need to support setting both of these to the custom credentials passed in.
> > In Python we can pass in a single credentials object because the `google-auth` library allows [credentials to be re-scoped](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/blob/main/google/cloud/sql/connector/refresh_utils.py#L198) (hence we can pass in a single credentials object and scope it as required to satisfy both auth credentials). I wonder if something similar is possible for the node [`google-auth-library`](https://www.npmjs.com/package/google-auth-library)?
> 
> Humm, When I tested this I did not encounter any issue. Let me check again

Sorry, I was not able to reproduce it. Can anyone help me to update this and what should be updated with? I only pass the loginAuth since the getEphemeralCertificate function would be able to use the passed in loginAuth and get the access token and the client.

**Comment by enocom** [comment]
The PR here might be a good thing to build on: https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector/pull/210 and will make it easy to pass in an auth object.

**Comment by Anoupz** [comment]
> The PR here might be a good thing to build on: #210 and will make it easy to pass in an auth object.

Thanks @enocom. @edosrecki you can combine these two changes or I can merge your changes on mine. Feel free to edit it.

**Comment by edosrecki** [comment]
@jackwotherspoon, @Anoupz,

Can't we do the following:

```ts
constructor(options?: { authClient?: AuthClient }) {
  const adminAuth = new GoogleAuth({
    authClient: options.authClient,
    scopes: ['https://www.googleapis.com/auth/sqlservice.admin'],
  });
  const loginAuth = new GoogleAuth({
    authClient: options.authClient,
    scopes: ['https://www.googleapis.com/auth/sqlservice.login'],
  })
 
  // ...
```

If a custom `AuthClient` object is passed by the library user, `GoogleAuth` class will use it, otherwise it will set it up by doing it's own magic.

**Comment by enocom** [comment]
That looks good to me. @ruyadorno WDYT?

**Comment by edosrecki** [comment]
@jackwotherspoon @enocom @ruyadorno @Anoupz 

I just tried out what I suggested above, and it does not work due to TypeScript error.

`Sqladmin` constructor expects `auth: GoogleAuth`, which is a generic type `GoogleAuth<T extends AuthClient = JSONClient>`. As you can see it is defaulted to `JSONClient` which is a union type `JSONClient = JWT | UserRefreshClient | BaseExternalAccountClient | ExternalAccountAuthorizedUserClient | Impersonated;`.

Therefore we cannot pass just _any_ `AuthClient`, but only those specified in `JSONClient` type. I believe this is a type mistake. I think that `Sqladmin` should be generic in `T extends AuthClient`, and should allow `auth: GoogleAuth<T>`.

I created an issue here: https://github.com/googleapis/google-api-nodejs-client/issues/3357 to start the discussion.

**Comment by ruyadorno** [comment]
@edosrecki @jackwotherspoon I also noticed that `google-auth-library` has a [DownscopedClient](https://github.com/googleapis/google-auth-library-nodejs#downscoped-client) that would be ideal to implement something similar to how it works on the Python Connector. Unfortunately it seems to use a `CredentialAccessBoundary` system that is only available on Cloud Storage for now.

**Pull request closed without merging**
