### PR TITLE
docs: add knex examples

### LINKED ISSUE #111: Document usage for Knex
Issue to track interest in support for [Knex.js](https://knexjs.org/) with the Cloud SQL Node.js Connector.

Upvoting this issue 👍 will help us prioritize support.

### PR DESCRIPTION
**Pull request by edosrecki**
## Change Description

Adds examples of using `cloud-sql-nodejs-connector` library with [`knex`](https://knexjs.org) for `pg`, `mysql2`, and `tedious` drivers.

## Checklist

- [x] Make sure to open an issue as a
  [bug/issue](https://github.com/GoogleCloudPlatform//issues/new/choose)
  before writing your code! That way we can discuss the change, evaluate
  designs, and agree on the general idea.
- [x] Ensure the tests and linter pass
- [x] Appropriate documentation is updated (if necessary)

## Relevant issues:

- Fixes #111

### CODE REVIEW

**Review by ruyadorno — COMMENTED** [review]
hi @edosrecki, thank you so much for your contribution! This looks great!

One detail that we may want to tweak in the samples is that we've been deliberately favouring usage of the spread object operator to pass around `stream` to the `connection` options object in order to have a more abstracted API that is easier for outside users to reason about (the `stream` property is just an internal detail that does not mean much for users):

```patch
-const {stream} = await connector.getOptions({});
+const clientOpts = await connector.getOptions({});
 const database = knex({
   client: 'mysql2',
   connection: {
+    ...clientOpts,
     user: 'my-service-account',
     database: 'my-database',
-    stream,
   },
 });
```

**Comment by edosrecki** [comment]
Hi @ruyadorno!

No problem, I just changed it based on your comment.

**Comment by ruyadorno** [comment]
Awesome! It looks great, thanks @edosrecki 

> I was also thinking whether you would prefer examples written in the form of tests (like system-test directory), and install required library (e.g. knex) in the CI worklow, or do you think that's too much?

I believe that's a bit too much, the goal is just to have some usage examples and this format looks good 😊

**Review by jackwotherspoon — COMMENTED** [review]
@edosrecki Thanks for this great PR, I'll let Ruy approve since he has already put some time into reviewing these. 

One question for the both of you, do we think maybe it would be best to have sub-folders within the `examples/` folder? Maybe a sub-folder for `postgres`, `mysql` and `sql-server`? Another option that might be better would be to have a sub-folder per ORM/library like `knex` and `sequelize` etc under `examples/`.  Just trying to think about if we add more examples how it will be easiest for users to find the sample they are looking for without having 30+ files within a single folder.

**Comment by edosrecki** [comment]
@jackwotherspoon, 

That's a great point. I would prefer having sub-folders per library. We have 3 databases, but in _Issues_ there are already discussion about at least 5 libraries, so from the cardinality point of view, I feel like that makes more sense.

**Comment by edosrecki** [comment]
@jackwotherspoon, @ruyadorno 

Moved knex examples to `examples/knex`.

**Comment by ruyadorno** [comment]
hi @edosrecki just wanted to follow up and let you know that we're planning on landing your example PRs after this week's release (it's a big milestone for us since the connector will be going `v1.0.0`). Rest assured that your contribution is very welcomed and we'll get it merged as soon as possible afterwards 😊

**Pull request closed without merging**
